version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-container
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html      # Map folder php ke /var/www/html dalam kontainer
      - ./config:/etc/apache2/sites-available   # Map folder config ke direktori konfigurasi Apache
    networks:
      - app-network
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: always

  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lofocam
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"
    restart: always

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
